package Interfaz;

public class menuAdmin extends javax.swing.JFrame {
    
    public menuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        // Inicializar el JComboBox1 (Rol)
        String[] roles = {"Administrador", "Recepcionista", "Personal de Limpieza", "Inspector"};
        for (String rol : roles) {
            jComboBox1.addItem(rol);
        }
    }
    
    // Método de Carga/Actualización (jList1)

    // Método auxiliar para limpiar campos
    private void limpiarCampos() {
        jTextField1.setText(""); // DNI
        jTextField2.setText(""); // Nombre Completo
        jComboBox1.setSelectedIndex(0);
        jTextField1.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel1.setText("Lista Empleados (Nombre - DNI):");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jLabel5.setText("DNI:");

        jLabel6.setText("Nombre: ");

        jLabel7.setText("Rol:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2))
                    .addComponent(JLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField1)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addComponent(jLabel6))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dni = jTextField1.getText().trim();
        String nombre = jTextField2.getText().trim();
        String rol = jComboBox1.getSelectedItem().toString();

        if (dni.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar DNI y Nombre Completo.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Verificar si el DNI ya existe
        if (listaEmpleados.encontrarEmpleadoPorDNI(dni) != null) {
            JOptionPane.showMessageDialog(this, "El DNI ya está registrado: " + dni, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Crear y agregar nuevo empleado (Usando constructores simplificados)
        try {
            String numContratoEjemplo = "NC" + dni.substring(0, 3); 
            
            switch (rol) {
                case "Administrador":
                    // cAdministrador(Nombre, DNI, Tel, Correo, NumContrato, Usuario, Contraseña)
                    listaEmpleados.getListaAdministradores().add(
                        new cAdministrador(nombre, dni, "999", "temp@admin.com", numContratoEjemplo, "user", "pass")
                    );
                    break;
                case "Recepcionista":
                    // cRecepcionista(Nombre, DNI, Tel, Correo, NumContrato, UsuarioR, ContraseñaR)
                    listaEmpleados.getListaRecepcionistas().agregarRecepcionista(
                        new cRecepcionista(nombre, dni, "999", "temp@rec.com", numContratoEjemplo, "userR", "passR")
                    );
                    break;
                case "Personal de Limpieza":
                    // cPersonalLimpieza(Nombre, DNI, Tel, Correo, NumContrato, Turno, HabAsignadas, HabLimpiadas)
                    listaEmpleados.getListaPersonalLimpieza().agregarPersonalLimpieza(
                        new cPersonalLimpieza(nombre, dni, "999", "temp@limp.com", numContratoEjemplo, "Día", 0, 0)
                    );
                    break;
                case "Inspector":
                    // cInspector(Nombre, DNI, Tel, Correo, NumContrato, PisosACargo, HabInspeccionadas)
                    listaEmpleados.getListaInspectores().agregarInspector(
                        new cInspector(nombre, dni, "999", "temp@insp.com", numContratoEjemplo, 1, 0)
                    );
                    break;
            }
            
            JOptionPane.showMessageDialog(this, "Empleado " + nombre + " agregado como " + rol + ".");
            listaEmpleados.calcularNumPersonal(); 
            cargarListaEmpleados(); 
            limpiarCampos();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al agregar empleado: " + e.getMessage(), "Error de Código", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String dni = jTextField1.getText().trim(); // DNI del empleado a buscar
        String nuevoNombre = jTextField2.getText().trim(); // Nuevo nombre

        if (dni.isEmpty() || nuevoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar DNI y el nuevo Nombre Completo.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        cEmpleado empleado = listaEmpleados.encontrarEmpleadoPorDNI(dni);

        if (empleado == null) {
            JOptionPane.showMessageDialog(this, "No se encontró ningún empleado con el DNI: " + dni, "No Encontrado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Usa el setter de cPersona/cEmpleado
            empleado.setNombreCompleto(nuevoNombre); 
            JOptionPane.showMessageDialog(this, "Nombre del empleado con DNI " + dni + " modificado a: " + nuevoNombre);
            cargarListaEmpleados(); 
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error de Implementación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String dni = jTextField1.getText().trim();
        String rol = jComboBox1.getSelectedItem().toString(); // Usado para saber de qué sub-lista eliminar

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el DNI del empleado a eliminar.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        cEmpleado empleado = listaEmpleados.encontrarEmpleadoPorDNI(dni);

        if (empleado == null) {
            JOptionPane.showMessageDialog(this, "No se encontró ningún empleado con el DNI: " + dni, "No Encontrado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Llama a tu lógica de eliminación
        if (listaEmpleados.eliminarEmpleadoDeLista(empleado, rol)) {
            JOptionPane.showMessageDialog(this, "Empleado con DNI " + dni + " eliminado correctamente.");
            listaEmpleados.calcularNumPersonal(); 
            cargarListaEmpleados();
            limpiarCampos();
        } else {
            // Falla si el rol seleccionado en jComboBox1 no es el rol real del empleado
            JOptionPane.showMessageDialog(this, "Error al eliminar. Verifique que el Rol seleccionado (" + rol + ") sea el correcto para el DNI: " + dni, "Error de Rol", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuAdmin().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
